name: $(Date:MMddyy)$(Rev:.rrrr)

trigger: none

stages:
- stage: __default
  jobs:
  - job: Job1
    pool:
      vmImage: windows-latest
    steps:
    - task: OneLocBuild@2
      inputs:
        locProj: 'Localize/LocProject.json'
        outDir: '$(Build.ArtifactStagingDirectory)'
        packageSourceAuth: 'patAuth'
        patVariable: '$(OneLocBuildPAT)'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'Get-Content -Path "C:\Repos\SWLoc\src\OneLocBuild\OneLocBuildClient\Program.cs"'
      env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'

